version: 2
jobs:
  build:
    docker:
      - image: ballerina/ballerina
    steps:
      - checkout
      - run:
          name: Build the project
          command: |
            echo ***************************************************************************'
            echo '******** Build the project using ballerina/ballerina docker image ********'
            echo ***************************************************************************'
            cd service-warriors
            ballerina build service-warriors.bal
